### ISSUE TITLE
Question: Benefit of Trigger*.Context in Action method

### ISSUE THREAD

**Issue by ImJohnMDaniel** [kofijohnson/Apex-MicroTrigger#2]
@kofijohnson - This is not an issue, just a question.

Can you explain why your pattern passes the various Trigger*.Context classes to the Action class as a parameter?  What is the value in passing that Context through to the Action?  It would appear, at first glance, that an Action run method could easy be setup to just be given the preselected scope of records.  Can you provide an example of when passing the Context as well would be helpful? 

Thanks for the help.  Cheers!

**Comment by kofijohnson** [comment]
Hi @ImJohnMDaniel,

This is a good question. In most of the case, the Actions will only need the preselected scope of the records. However, the developer may need the Context to  access the other state (in newMap or oldMap) of the preselected records. Example requirement... Eg. Given a MicroTrigger that runs on AfterUpdate of Contacts records.
     - Criteria : AccountId has changed.
     - Action1 : Update some Fields on the Account of the Old Contact (oldMap)
     - Action2: Update some Fields on the Account of the New Contact (newMap)
In one of the Actions above, the developer will need to get the Old State (from oldMap) or New State (from newMap) of the preselected records, from the Context.

I think I get your point... The downside of giving the Context to the Actions is the Actions will have access to all the context records. And I can't think of any scenario where an Action will need to have access to the Context records other than the preselected ones.

Let me know your thoughts. Thanks @ImJohnMDaniel for your contribution.

**Comment by kofijohnson** [comment]
Hi @ImJohnMDaniel, let me know if my comment answers your question, and I will close this issue :)

**Comment by ImJohnMDaniel** [comment]
Hey @kofijohnson thanks for following up and my apologies for not responding before now.  Got distracted on other things.

My suggestion would be that if the Action classes actually don't require the Context object, you should remove it from the framework.  That way, the actions could be reused outside of a Trigger context on a "one-off" use case as needed.  

It would seem to me that Action interface could be reduced to following method signature.
`Boolean run (List<SObject>)`

Maybe have a second interface for actions that need access to the "existing records" (e.g. records that come from Trigger.oldMap).  The second interface would extend the first Action interface and add a new method of "setExistingRecords(List<SObject>)".  Having said that, I still don't know of a good use case where they would need access to the existing records.  That is not to say that there is not a good use case; I just usually use the existing records/trigger.oldMap in the "criteria" phase of this logic flow.

Thoughts?

**Comment by kofijohnson** [comment]
Thanks @ImJohnMDaniel for your ideas. We really appreciate it. I will check with the team, and review the impact of the change.
