### ISSUE TITLE
Licensing for large enterprise usage

### ISSUE THREAD

**Issue by Sriram-Venkatraman-Personal** [kofijohnson/Apex-MicroTrigger#3]
This framework is great and would love to use it. It enforces a discipline naturally when coding Triggers. Is there any plans to extend the licensing under MIT or Apache so larger enterprises could use them?

**Comment by kofijohnson** [comment]
Hi @Sriram-Venkatraman-Personal,
Thanks for your interest and contribution. The MicroTrigger framework uses [AGPL](https://www.gnu.org/licenses/agpl-3.0.en.html), which is a free license; Any type of enterprise can use the framework.
We don't have any plans to change the license. Please let us know if you have any concerns.

**Comment by kofijohnson** [comment]
Hi @Sriram-Venkatraman-Personal 
The license is updated from [AGPL](https://www.gnu.org/licenses/agpl-3.0.en.html) to [GPL V3](https://www.gnu.org/licenses/gpl-3.0.en.html). Let me know if you have any questions/concerns
