### ISSUE TITLE
Any support for Upsert operation?

### ISSUE THREAD

**Issue by EulogioGallo** [kofijohnson/Apex-MicroTrigger#4]
Are there any plans for implementing Upsert classes?  E.G. TriggerAfterUpsert, TriggerBeforeUpsert, etc.  I'm currently just implementing the Insert and Update classes for each instance of an Upsert I have.

Otherwise I'm really enjoying this framework so far, great job!

Eulogio #

**Comment by kofijohnson** [comment]
Hi @EulogioGallo, 
To do the Upsert, your Criteria class can implement both TriggerAfterInsert.Criteria, TriggerAfterUpdate.Criteria. Same for Action (TriggerAfterInsert.Action, TriggerAfterUpdate.Action).

Here is an example of Upsert implementation: https://github.com/kofijohnson/Apex-MicroTrigger-Examples/blob/master/Rollups/main/default/classes/AccountPayment_MT.cls
