### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by adesotamn** [kofijohnson/Apex-MicroTrigger#5]
I'm working on implementing this framework at my work and it appears that I need to create a base trigger for it to work correctly.  Can you provide a code sample of what Trigger code would look like?

**Comment by kofijohnson** [comment]
Hi @adesotamn,
Thanks for contributing. You are right, you will need to create a base Trigger for it to work. Here is an example of a base Apex Trigger for Account:

```apex
trigger AccountTrigger on Account (before insert, before update, before delete, after insert, after update, after delete, after undelete) {
    MicroTriggersDispatcher dispatcher = new MicroTriggersDispatcher();
    dispatcher.dispatch();
}
```

A Trigger for Contact would look like:

```apex
trigger ContactTrigger on Contact (before insert, before update, before delete, after insert, after update, after delete, after undelete) {
    MicroTriggersDispatcher dispatcher = new MicroTriggersDispatcher();
    dispatcher.dispatch();
}
```

Please note that you will need to do this only once. I will create a new Repo soon with some examples. I will keep you updated.

Thanks
